server:
  servlet:
    context-path: /
file:
  upload:
    path: D:/aitong/upload
    relative:
      path: /upload/**

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authoritymanagement?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password:
    # 创建数据库  初始数据  由sql脚本创建：initialization-mode设置为always
    # 也可以只初始化数据，则注释掉schema
    # 若由实体Bean映射自动创建表，则initialization-mode设置为never
    initialization-mode: never
#    data: classpath*:/db-import.sql
#    schema: classpath*:/db-schema.sql

  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      # 若由实体Bean自动创建表，则ddl-auto设置为always，如果由脚本创建表，则设置为none
      ddl-auto: update
    show-sql: true
    open-in-view: true


  thymeleaf:
    cache: false
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: utf-8

#  redis:
#    host: localhost #此为默认值
#    port: 6379 #此为默认值
#    database: 0 #此为默认值
#    password: #此为默认值
#    timeout: 30000s #连接超时时间，默认1天
#    lettuce:
#      shutdown-timeout: 100ms #关闭超时时间 默认100ms
#      pool:
#        max-active: 8 # 连接池最大连接数 默认 8（-1 ：表示没有限制）
#        max-wait: 60000ms # 连接池最大阻塞等待时间 默认-1ms （-1 :表示没有限制） 这里设置1分钟
#        max-idle: 8 # 最大空闲连接  默认 8
#        min-idle: 0 # 最小空闲连接  默认 0
